[config]
schemaVersion = "0.0.1"

[package]
namespace = "Caioreix"
name = "CoffinSleep"
versionNumber = "0.0.0"
description = "A VRising mod that speeds up time while you sleep in your coffin."
websiteUrl = "https://github.com/caioreix/CoffinSleep"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"
deca-Bloodstone = "0.1.4"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]
categories = []